#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#define ALPHABET_SIZE 26
#define MAX_WORD_LENGTH 50

typedef struct Node {
  bool last;
  struct Node *childs[ALPHABET_SIZE];
} Node;

static int is_valid_word_az(const char *word) {
  if (!word || *word == '\0')
    return 0;

  for (const unsigned char *p = (const unsigned char *)word; *p; p++) {
    if (*p < 'a' || *p > 'z')
      return 0;
  }

  return 1;
}

int readInput(char *input) {
  if (!fgets(input, MAX_WORD_LENGTH + 1, stdin)) {
    return 1;
  }

  char *newLine = strchr(input, '\n');

  if (newLine) {
    *newLine = '\0';
  } else {
    int c;

    while ((c = getchar()) != '\n' && c != EOF)
      ;

    printf("Error: max input size is %d characters\n", MAX_WORD_LENGTH);
    return 2;
  }

  return 0;
}

Node *create_node() {
  Node *new_node = malloc(sizeof(Node));

  if (!new_node)
    exit(1);

  new_node->last = 0;

  for (int i = 0; i < ALPHABET_SIZE; i++) {
    new_node->childs[i] = NULL;
  }

  return new_node;
}

Node *insert_word(Node *parent, const char *word) {
  if (parent == NULL) {
    parent = create_node();
  }

  if (*word == '\0') {
    parent->last = 1;
    return parent;
  }

  int i = (int)(*word - 'a');
  parent->childs[i] = insert_word(parent->childs[i], word + 1);

  return parent;
}

// NOTE: This printer is generated/modified by OpenCode.
// It prints a compact trie (radix-style): single-child chains are collapsed
// into one horizontal label, and branching only appears when there is a real
// bifurcation or a word end.
void print_words(Node *parent, char c, char *prefix, int prefix_len,
                 int is_last) {
  if (!parent)
    return;

  // Build a compact label by walking down while:
  // - not at word end
  // - exactly one child
  char letters[MAX_WORD_LENGTH + 1];
  int letters_len = 0;
  letters[letters_len++] = c;

  Node *cur = parent;
  while (!cur->last) {
    int only_child = -1;
    int count = 0;
    for (int j = 0; j < ALPHABET_SIZE; j++) {
      if (cur->childs[j]) {
        only_child = j;
        count++;
        if (count > 1)
          break;
      }
    }

    if (count != 1)
      break;
    if (letters_len >= MAX_WORD_LENGTH)
      break;

    letters[letters_len++] = (char)('a' + only_child);
    cur = cur->childs[only_child];
  }

  // NOTE (generated by OpenCode): Render letters connected by horizontal lines
  // instead of glued text (e.g. a──u──d──i).
  const char *h2 = "\xe2\x94\x80\xe2\x94\x80"; // "──"
  char label[MAX_WORD_LENGTH * 4 + 1];
  int label_pos = 0;
  if (letters_len > 0) {
    label[label_pos++] = letters[0];
    for (int i = 1; i < letters_len; i++) {
      for (int k = 0; h2[k]; k++) {
        if (label_pos >= (int)sizeof(label) - 1)
          break;
        label[label_pos++] = h2[k];
      }
      if (label_pos >= (int)sizeof(label) - 1)
        break;
      label[label_pos++] = letters[i];
    }
  }
  label[label_pos] = '\0';

  char line[MAX_WORD_LENGTH * 4 + 10];
  int pos = 0;
  for (int i = 0; i < prefix_len; i++) {
    line[pos++] = prefix[i];
  }

  const char *connector = is_last
                              ? "\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 "  // └──
                              : "\xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 "; // ├──
  for (int k = 0; connector[k]; k++)
    line[pos++] = connector[k];

  line[pos] = '\0';
  printf("%s%s%s\n", line, label, cur->last ? " *" : "");

  int last_child = -1;
  for (int j = 0; j < ALPHABET_SIZE; j++) {
    if (cur->childs[j])
      last_child = j;
  }

  char new_prefix[MAX_WORD_LENGTH * 4 + 10];
  int new_len = 0;
  for (int i = 0; i < prefix_len; i++) {
    new_prefix[new_len++] = prefix[i];
  }

  const char *extension = is_last ? "    " : "\xe2\x94\x82   ";
  for (int k = 0; extension[k]; k++)
    new_prefix[new_len++] = extension[k];

  // NOTE (generated by OpenCode): shift child branches so they visually emerge
  // from the *end* of the compact label (last letter), not from the first.
  // Display width of our label is: letters + 2*(letters-1) = 3*letters-2.
  // We pad with (width-1) spaces so the next connector aligns under the last
  // letter position.
  int label_width = (letters_len > 0) ? (3 * letters_len - 2) : 0;
  int pad_spaces = (label_width > 0) ? (label_width - 1) : 0;
  for (int i = 0; i < pad_spaces; i++) {
    if (new_len >= (int)sizeof(new_prefix) - 1)
      break;
    new_prefix[new_len++] = ' ';
  }

  for (int j = 0; j < ALPHABET_SIZE; j++) {
    if (cur->childs[j]) {
      print_words(cur->childs[j], (char)('a' + j), new_prefix, new_len,
                  j == last_child);
    }
  }
}

void free_trie(Node *root) {
  if (!root)
    return;

  for (int i = 0; i < ALPHABET_SIZE; i++) {
    free_trie(root->childs[i]);
  }

  free(root);
}

// NOTE (generated by OpenCode): If you ever want to validate content as a flat
// word list (one per line), reintroduce a DFS printer here. For now we print
// with the `tree`-style view via print_words().

int main(void) {
  char current_word[MAX_WORD_LENGTH + 1];
  Node *trie = create_node();
  // Node *trie = NULL;

  printf("Insert a word to store in trie, or '0' to exit:\n");

  while (1) {
    printf(">>> ");
    readInput(current_word);

    if (!strcmp("0", current_word) || strlen(current_word) > MAX_WORD_LENGTH)
      break;

    if (!is_valid_word_az(current_word)) {
      printf("Error: only lowercase a-z allowed\n");
      continue;
    }

    trie = insert_word(trie, current_word);
  }

  printf(".\n");

  int last_child = -1;
  for (int j = 0; j < ALPHABET_SIZE; j++) {
    if (trie->childs[j])
      last_child = j;
  }

  char prefix[1] = {0};
  for (int j = 0; j < ALPHABET_SIZE; j++) {
    if (trie->childs[j]) {
      print_words(trie->childs[j], (char)('a' + j), prefix, 0, j == last_child);
    }
  }

  free_trie(trie);

  return EXIT_SUCCESS;
}
